name: TrashMap

on:  
  push:
    #    tags:
    #      - '*'

jobs:
  build:
    name: ImageMap build
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgis/postgis:latest
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go 
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
      
      - name: Build & Test
        run: |
          go mod tidy -compat=1.17
          go test -v -race -count 1 ./...
          go build -v -ldflags="-s -w" ./...

  release:
    name: ImageMap release
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go 
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --config .goreleaser.yaml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
